// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rNormalGLM_cpp_export
Rcpp::List rNormalGLM_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double dispersion, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::NumericVector& start, const std::string& family, const std::string& link, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_rNormalGLM_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP startSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGLM_cpp_export(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rNormalGLMBlocks_cpp_export
Rcpp::List rNormalGLMBlocks_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& dispersion, const Rcpp::NumericMatrix& mu, const Rcpp::List& P_blocks, bool prior_by_block, const Rcpp::List& row_blocks, const Rcpp::Function& f2, const Rcpp::Function& f3, const std::string& family, const std::string& link, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_rNormalGLMBlocks_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP muSEXP, SEXP P_blocksSEXP, SEXP prior_by_blockSEXP, SEXP row_blocksSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type P_blocks(P_blocksSEXP);
    Rcpp::traits::input_parameter< bool >::type prior_by_block(prior_by_blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type row_blocks(row_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGLMBlocks_cpp_export(n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rNormalRegBlocks_cpp_export
Rcpp::List rNormalRegBlocks_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& dispersion, const Rcpp::NumericMatrix& mu, const Rcpp::List& P_blocks, bool prior_by_block, const Rcpp::List& row_blocks, const Rcpp::Function& f2, const Rcpp::Function& f3, int Gridtype);
RcppExport SEXP _glmbayesCore_rNormalRegBlocks_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP muSEXP, SEXP P_blocksSEXP, SEXP prior_by_blockSEXP, SEXP row_blocksSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP GridtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type P_blocks(P_blocksSEXP);
    Rcpp::traits::input_parameter< bool >::type prior_by_block(prior_by_blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type row_blocks(row_blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalRegBlocks_cpp_export(n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, Gridtype));
    return rcpp_result_gen;
END_RCPP
}
// block_rNormalReg_cpp_export
Rcpp::List block_rNormalReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, SEXP block, SEXP prior_list, SEXP prior_lists, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::Function& f3, int Gridtype);
RcppExport SEXP _glmbayesCore_block_rNormalReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP blockSEXP, SEXP prior_listSEXP, SEXP prior_listsSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP GridtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prior_list(prior_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prior_lists(prior_listsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(block_rNormalReg_cpp_export(n, y, x, block, prior_list, prior_lists, offset, wt, f2, f3, Gridtype));
    return rcpp_result_gen;
END_RCPP
}
// block_rNormalGLM_cpp_export
Rcpp::List block_rNormalGLM_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, SEXP block, SEXP prior_list, SEXP prior_lists, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::Function& f3, const std::string& family, const std::string& link, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_block_rNormalGLM_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP blockSEXP, SEXP prior_listSEXP, SEXP prior_listsSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prior_list(prior_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prior_lists(prior_listsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(block_rNormalGLM_cpp_export(n, y, x, block, prior_list, prior_lists, offset, wt, f2, f3, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// two_block_rNormal_reg_cpp_export
Rcpp::List two_block_rNormal_reg_cpp_export(int n, int m_convergence, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, SEXP block, const Rcpp::List& x_hyper, const Rcpp::List& prior_list_block1, SEXP dispersion_block1, SEXP ddef_block1, const Rcpp::List& prior_list_block2, const Rcpp::List& fixef_start, const Rcpp::CharacterVector& group_levels, const std::string& family, const std::string& link, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose, bool progbar);
RcppExport SEXP _glmbayesCore_two_block_rNormal_reg_cpp_export(SEXP nSEXP, SEXP m_convergenceSEXP, SEXP ySEXP, SEXP xSEXP, SEXP blockSEXP, SEXP x_hyperSEXP, SEXP prior_list_block1SEXP, SEXP dispersion_block1SEXP, SEXP ddef_block1SEXP, SEXP prior_list_block2SEXP, SEXP fixef_startSEXP, SEXP group_levelsSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP, SEXP progbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m_convergence(m_convergenceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior_list_block1(prior_list_block1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dispersion_block1(dispersion_block1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ddef_block1(ddef_block1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior_list_block2(prior_list_block2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef_start(fixef_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_rNormal_reg_cpp_export(n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, prior_list_block2, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar));
    return rcpp_result_gen;
END_RCPP
}
// two_block_rNormal_reg_v2_cpp_export
Rcpp::List two_block_rNormal_reg_v2_cpp_export(int n, int m_convergence, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, SEXP block, const Rcpp::List& x_hyper, const Rcpp::List& prior_list_block1, SEXP dispersion_block1, SEXP ddef_block1, const Rcpp::List& pfamily_list, const Rcpp::List& fixef_start, const Rcpp::CharacterVector& group_levels, const std::string& family, const std::string& link, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose, bool progbar);
RcppExport SEXP _glmbayesCore_two_block_rNormal_reg_v2_cpp_export(SEXP nSEXP, SEXP m_convergenceSEXP, SEXP ySEXP, SEXP xSEXP, SEXP blockSEXP, SEXP x_hyperSEXP, SEXP prior_list_block1SEXP, SEXP dispersion_block1SEXP, SEXP ddef_block1SEXP, SEXP pfamily_listSEXP, SEXP fixef_startSEXP, SEXP group_levelsSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP, SEXP progbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m_convergence(m_convergenceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior_list_block1(prior_list_block1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dispersion_block1(dispersion_block1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ddef_block1(ddef_block1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pfamily_list(pfamily_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef_start(fixef_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_rNormal_reg_v2_cpp_export(n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar));
    return rcpp_result_gen;
END_RCPP
}
// two_block_rNormal_reg_v5_cpp_export
Rcpp::List two_block_rNormal_reg_v5_cpp_export(int n, int m_convergence, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, SEXP block, const Rcpp::List& x_hyper, const Rcpp::List& prior_list_block1, SEXP dispersion_block1, SEXP ddef_block1, const Rcpp::List& pfamily_list, const Rcpp::List& fixef_start, const Rcpp::CharacterVector& group_levels, const std::string& family, const std::string& link, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose, Rcpp::Nullable<int> seed, int seed_offset, bool progbar, std::string stage_label, bool diag_sweeps, SEXP fixef_mode, SEXP b_mode);
RcppExport SEXP _glmbayesCore_two_block_rNormal_reg_v5_cpp_export(SEXP nSEXP, SEXP m_convergenceSEXP, SEXP ySEXP, SEXP xSEXP, SEXP blockSEXP, SEXP x_hyperSEXP, SEXP prior_list_block1SEXP, SEXP dispersion_block1SEXP, SEXP ddef_block1SEXP, SEXP pfamily_listSEXP, SEXP fixef_startSEXP, SEXP group_levelsSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP, SEXP seedSEXP, SEXP seed_offsetSEXP, SEXP progbarSEXP, SEXP stage_labelSEXP, SEXP diag_sweepsSEXP, SEXP fixef_modeSEXP, SEXP b_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m_convergence(m_convergenceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior_list_block1(prior_list_block1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dispersion_block1(dispersion_block1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ddef_block1(ddef_block1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pfamily_list(pfamily_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef_start(fixef_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type seed_offset(seed_offsetSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< std::string >::type stage_label(stage_labelSEXP);
    Rcpp::traits::input_parameter< bool >::type diag_sweeps(diag_sweepsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fixef_mode(fixef_modeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_mode(b_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_rNormal_reg_v5_cpp_export(n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, seed, seed_offset, progbar, stage_label, diag_sweeps, fixef_mode, b_mode));
    return rcpp_result_gen;
END_RCPP
}
// two_block_rNormal_reg_staged_cpp_export
Rcpp::List two_block_rNormal_reg_staged_cpp_export(int n_main, int m_convergence_main, int n_pilot, int m_convergence_pilot, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::RObject& block, const Rcpp::List& x_hyper, const Rcpp::List& prior_list_block1, const Rcpp::RObject& dispersion_block1, const Rcpp::RObject& ddef_block1, const Rcpp::List& pfamily_list, const Rcpp::List& fixef_start, const Rcpp::CharacterVector& group_levels, const std::string& family, const std::string& link, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose, bool progbar_main, bool progbar_pilot);
RcppExport SEXP _glmbayesCore_two_block_rNormal_reg_staged_cpp_export(SEXP n_mainSEXP, SEXP m_convergence_mainSEXP, SEXP n_pilotSEXP, SEXP m_convergence_pilotSEXP, SEXP ySEXP, SEXP xSEXP, SEXP blockSEXP, SEXP x_hyperSEXP, SEXP prior_list_block1SEXP, SEXP dispersion_block1SEXP, SEXP ddef_block1SEXP, SEXP pfamily_listSEXP, SEXP fixef_startSEXP, SEXP group_levelsSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP, SEXP progbar_mainSEXP, SEXP progbar_pilotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_main(n_mainSEXP);
    Rcpp::traits::input_parameter< int >::type m_convergence_main(m_convergence_mainSEXP);
    Rcpp::traits::input_parameter< int >::type n_pilot(n_pilotSEXP);
    Rcpp::traits::input_parameter< int >::type m_convergence_pilot(m_convergence_pilotSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RObject& >::type block(blockSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type prior_list_block1(prior_list_block1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::RObject& >::type dispersion_block1(dispersion_block1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::RObject& >::type ddef_block1(ddef_block1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pfamily_list(pfamily_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef_start(fixef_startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar_main(progbar_mainSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar_pilot(progbar_pilotSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_rNormal_reg_staged_cpp_export(n_main, m_convergence_main, n_pilot, m_convergence_pilot, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar_main, progbar_pilot));
    return rcpp_result_gen;
END_RCPP
}
// two_block_build_mu_all_cpp_export
Rcpp::NumericMatrix two_block_build_mu_all_cpp_export(const Rcpp::List& x_hyper, const Rcpp::List& fixef, const Rcpp::CharacterVector& re_names, const Rcpp::CharacterVector& group_levels);
RcppExport SEXP _glmbayesCore_two_block_build_mu_all_cpp_export(SEXP x_hyperSEXP, SEXP fixefSEXP, SEXP re_namesSEXP, SEXP group_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef(fixefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_build_mu_all_cpp_export(x_hyper, fixef, re_names, group_levels));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block1_prior_with_tau2_cpp_export
Rcpp::List two_block_block1_prior_with_tau2_cpp_export(const Rcpp::List& base_prior, const Rcpp::NumericVector& tau2_vec, const Rcpp::CharacterVector& ptypes, const Rcpp::CharacterVector& re_names, const Rcpp::NumericMatrix& mu_all);
RcppExport SEXP _glmbayesCore_two_block_block1_prior_with_tau2_cpp_export(SEXP base_priorSEXP, SEXP tau2_vecSEXP, SEXP ptypesSEXP, SEXP re_namesSEXP, SEXP mu_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type base_prior(base_priorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau2_vec(tau2_vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ptypes(ptypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu_all(mu_allSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block1_prior_with_tau2_cpp_export(base_prior, tau2_vec, ptypes, re_names, mu_all));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block1_iters_mean_cpp_export
double two_block_block1_iters_mean_cpp_export(const Rcpp::List& block_out);
RcppExport SEXP _glmbayesCore_two_block_block1_iters_mean_cpp_export(SEXP block_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type block_out(block_outSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block1_iters_mean_cpp_export(block_out));
    return rcpp_result_gen;
END_RCPP
}
// two_block_batch_tau2_chain_row_cpp_export
Rcpp::NumericVector two_block_batch_tau2_chain_row_cpp_export(const Rcpp::NumericMatrix& batch_tau2, int chain_i);
RcppExport SEXP _glmbayesCore_two_block_batch_tau2_chain_row_cpp_export(SEXP batch_tau2SEXP, SEXP chain_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type batch_tau2(batch_tau2SEXP);
    Rcpp::traits::input_parameter< int >::type chain_i(chain_iSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_batch_tau2_chain_row_cpp_export(batch_tau2, chain_i));
    return rcpp_result_gen;
END_RCPP
}
// two_block_batch_b_assign_slice_cpp_export
Rcpp::NumericVector two_block_batch_b_assign_slice_cpp_export(Rcpp::NumericVector b_store, int chain_i, Rcpp::NumericMatrix b_draw);
RcppExport SEXP _glmbayesCore_two_block_batch_b_assign_slice_cpp_export(SEXP b_storeSEXP, SEXP chain_iSEXP, SEXP b_drawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_store(b_storeSEXP);
    Rcpp::traits::input_parameter< int >::type chain_i(chain_iSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b_draw(b_drawSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_batch_b_assign_slice_cpp_export(b_store, chain_i, b_draw));
    return rcpp_result_gen;
END_RCPP
}
// two_block_batch_iters_ranef_add_cpp_export
Rcpp::NumericVector two_block_batch_iters_ranef_add_cpp_export(Rcpp::NumericVector iters_ranef, int chain_i, double iters_mean);
RcppExport SEXP _glmbayesCore_two_block_batch_iters_ranef_add_cpp_export(SEXP iters_ranefSEXP, SEXP chain_iSEXP, SEXP iters_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iters_ranef(iters_ranefSEXP);
    Rcpp::traits::input_parameter< int >::type chain_i(chain_iSEXP);
    Rcpp::traits::input_parameter< double >::type iters_mean(iters_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_batch_iters_ranef_add_cpp_export(iters_ranef, chain_i, iters_mean));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block1_one_chain_draw_cpp_export
Rcpp::List two_block_block1_one_chain_draw_cpp_export(int chain_i, const Rcpp::List& batch_fixef, const Rcpp::NumericVector& tau2_i, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& Z, SEXP groups, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, const Rcpp::List& x_hyper, const Rcpp::CharacterVector& re_names, const Rcpp::CharacterVector& group_levels, const Rcpp::CharacterVector& ptypes, const Rcpp::List& block1_prior, bool is_gaussian, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss, const std::string& family, const std::string& link, int Gridtype, int n_envopt);
RcppExport SEXP _glmbayesCore_two_block_block1_one_chain_draw_cpp_export(SEXP chain_iSEXP, SEXP batch_fixefSEXP, SEXP tau2_iSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP groupsSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP x_hyperSEXP, SEXP re_namesSEXP, SEXP group_levelsSEXP, SEXP ptypesSEXP, SEXP block1_priorSEXP, SEXP is_gaussianSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chain_i(chain_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type batch_fixef(batch_fixefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau2_i(tau2_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ptypes(ptypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type block1_prior(block1_priorSEXP);
    Rcpp::traits::input_parameter< bool >::type is_gaussian(is_gaussianSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block1_one_chain_draw_cpp_export(chain_i, batch_fixef, tau2_i, y, Z, groups, offset, wt, x_hyper, re_names, group_levels, ptypes, block1_prior, is_gaussian, f2, f3, f2_gauss, f3_gauss, family, link, Gridtype, n_envopt));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block1_one_chain_cpp_export
Rcpp::List two_block_block1_one_chain_cpp_export(int chain_i, Rcpp::NumericVector b_store, Rcpp::NumericVector iters_ranef, const Rcpp::List& batch_fixef, const Rcpp::NumericMatrix& batch_tau2, const Rcpp::List& design, const Rcpp::List& block1_prior, SEXP family, const Rcpp::CharacterVector& ptypes, const Rcpp::CharacterVector& re_names, const Rcpp::CharacterVector& group_levels, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss, bool use_cpp_tau2_row, bool use_cpp_b_slice, bool use_cpp_iters_ranef_add);
RcppExport SEXP _glmbayesCore_two_block_block1_one_chain_cpp_export(SEXP chain_iSEXP, SEXP b_storeSEXP, SEXP iters_ranefSEXP, SEXP batch_fixefSEXP, SEXP batch_tau2SEXP, SEXP designSEXP, SEXP block1_priorSEXP, SEXP familySEXP, SEXP ptypesSEXP, SEXP re_namesSEXP, SEXP group_levelsSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP, SEXP use_cpp_tau2_rowSEXP, SEXP use_cpp_b_sliceSEXP, SEXP use_cpp_iters_ranef_addSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type chain_i(chain_iSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_store(b_storeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iters_ranef(iters_ranefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type batch_fixef(batch_fixefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type batch_tau2(batch_tau2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type block1_prior(block1_priorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ptypes(ptypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cpp_tau2_row(use_cpp_tau2_rowSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cpp_b_slice(use_cpp_b_sliceSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cpp_iters_ranef_add(use_cpp_iters_ranef_addSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block1_one_chain_cpp_export(chain_i, b_store, iters_ranef, batch_fixef, batch_tau2, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block1_one_chain_v2_cpp_export
Rcpp::List two_block_block1_one_chain_v2_cpp_export(const Rcpp::List& fixef_i, const Rcpp::NumericVector& tau2_i, const Rcpp::List& design, const Rcpp::List& block1_prior, SEXP family, const Rcpp::CharacterVector& ptypes, const Rcpp::CharacterVector& re_names, const Rcpp::CharacterVector& group_levels, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::Function& f2_gauss, const Rcpp::Function& f3_gauss);
RcppExport SEXP _glmbayesCore_two_block_block1_one_chain_v2_cpp_export(SEXP fixef_iSEXP, SEXP tau2_iSEXP, SEXP designSEXP, SEXP block1_priorSEXP, SEXP familySEXP, SEXP ptypesSEXP, SEXP re_namesSEXP, SEXP group_levelsSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP f2_gaussSEXP, SEXP f3_gaussSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef_i(fixef_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau2_i(tau2_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type block1_prior(block1_priorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ptypes(ptypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2_gauss(f2_gaussSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3_gauss(f3_gaussSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block1_one_chain_v2_cpp_export(fixef_i, tau2_i, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block1_all_chains_cpp_export
Rcpp::List two_block_block1_all_chains_cpp_export(int n, const Rcpp::List& fixef, const Rcpp::NumericMatrix& tau2, Rcpp::NumericVector b, Rcpp::NumericVector iters_ranef, const Rcpp::CharacterVector& re_names, const Rcpp::CharacterVector& group_levels, const Rcpp::List& design, const Rcpp::List& block1_prior, SEXP family, const Rcpp::CharacterVector& ptypes, bool use_cpp_tau2_row, bool use_cpp_b_slice, bool use_cpp_iters_ranef_add, bool show_bar, const std::string& progbar_prefix, bool progbar_finish_newline);
RcppExport SEXP _glmbayesCore_two_block_block1_all_chains_cpp_export(SEXP nSEXP, SEXP fixefSEXP, SEXP tau2SEXP, SEXP bSEXP, SEXP iters_ranefSEXP, SEXP re_namesSEXP, SEXP group_levelsSEXP, SEXP designSEXP, SEXP block1_priorSEXP, SEXP familySEXP, SEXP ptypesSEXP, SEXP use_cpp_tau2_rowSEXP, SEXP use_cpp_b_sliceSEXP, SEXP use_cpp_iters_ranef_addSEXP, SEXP show_barSEXP, SEXP progbar_prefixSEXP, SEXP progbar_finish_newlineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef(fixefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iters_ranef(iters_ranefSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type design(designSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type block1_prior(block1_priorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ptypes(ptypesSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cpp_tau2_row(use_cpp_tau2_rowSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cpp_b_slice(use_cpp_b_sliceSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cpp_iters_ranef_add(use_cpp_iters_ranef_addSEXP);
    Rcpp::traits::input_parameter< bool >::type show_bar(show_barSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type progbar_prefix(progbar_prefixSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar_finish_newline(progbar_finish_newlineSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block1_all_chains_cpp_export(n, fixef, tau2, b, iters_ranef, re_names, group_levels, design, block1_prior, family, ptypes, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add, show_bar, progbar_prefix, progbar_finish_newline));
    return rcpp_result_gen;
END_RCPP
}
// two_block_reorder_b_to_group_levels_cpp_export
Rcpp::NumericMatrix two_block_reorder_b_to_group_levels_cpp_export(Rcpp::NumericMatrix b_draw, SEXP block_ids, Rcpp::CharacterVector group_levels);
RcppExport SEXP _glmbayesCore_two_block_reorder_b_to_group_levels_cpp_export(SEXP b_drawSEXP, SEXP block_idsSEXP, SEXP group_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b_draw(b_drawSEXP);
    Rcpp::traits::input_parameter< SEXP >::type block_ids(block_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type group_levels(group_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_reorder_b_to_group_levels_cpp_export(b_draw, block_ids, group_levels));
    return rcpp_result_gen;
END_RCPP
}
// two_block_align_b_to_xhyper_cpp_export
Rcpp::NumericVector two_block_align_b_to_xhyper_cpp_export(Rcpp::NumericVector b_vec, Rcpp::NumericMatrix X_k, Rcpp::CharacterVector group_levels);
RcppExport SEXP _glmbayesCore_two_block_align_b_to_xhyper_cpp_export(SEXP b_vecSEXP, SEXP X_kSEXP, SEXP group_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_vec(b_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_k(X_kSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type group_levels(group_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_align_b_to_xhyper_cpp_export(b_vec, X_k, group_levels));
    return rcpp_result_gen;
END_RCPP
}
// two_block_block2_one_chain_cpp_export
Rcpp::List two_block_block2_one_chain_cpp_export(const Rcpp::NumericMatrix& b_i, const Rcpp::List& fixef_rows, const Rcpp::NumericVector& tau2_i, const Rcpp::NumericVector& iters_i, const Rcpp::List& x_hyper, const Rcpp::CharacterVector& group_levels, const Rcpp::List& pfamily_list, const Rcpp::CharacterVector& ptypes, const Rcpp::CharacterVector& re_names);
RcppExport SEXP _glmbayesCore_two_block_block2_one_chain_cpp_export(SEXP b_iSEXP, SEXP fixef_rowsSEXP, SEXP tau2_iSEXP, SEXP iters_iSEXP, SEXP x_hyperSEXP, SEXP group_levelsSEXP, SEXP pfamily_listSEXP, SEXP ptypesSEXP, SEXP re_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type b_i(b_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type fixef_rows(fixef_rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tau2_i(tau2_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type iters_i(iters_iSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type x_hyper(x_hyperSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_levels(group_levelsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pfamily_list(pfamily_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ptypes(ptypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type re_names(re_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(two_block_block2_one_chain_cpp_export(b_i, fixef_rows, tau2_i, iters_i, x_hyper, group_levels, pfamily_list, ptypes, re_names));
    return rcpp_result_gen;
END_RCPP
}
// rNormalReg_cpp_export
Rcpp::List rNormalReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double dispersion, const Rcpp::Function& f2, const Rcpp::Function& f3, const Rcpp::NumericVector& start, const std::string& family, const std::string& link, int Gridtype);
RcppExport SEXP _glmbayesCore_rNormalReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP dispersionSEXP, SEXP f2SEXP, SEXP f3SEXP, SEXP startSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f3(f3SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalReg_cpp_export(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype));
    return rcpp_result_gen;
END_RCPP
}
// rIndepNormalGammaReg_cpp_export
Rcpp::List rIndepNormalGammaReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double shape, double rate, double max_disp_perc, Rcpp::Nullable<Rcpp::NumericVector> disp_lower, Rcpp::Nullable<Rcpp::NumericVector> disp_upper, int Gridtype, int n_envopt, bool use_parallel, bool use_opencl, bool verbose, bool progbar);
RcppExport SEXP _glmbayesCore_rIndepNormalGammaReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP, SEXP progbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    rcpp_result_gen = Rcpp::wrap(rIndepNormalGammaReg_cpp_export(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar));
    return rcpp_result_gen;
END_RCPP
}
// rNormalGammaReg_cpp_export
Rcpp::List rNormalGammaReg_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double shape, double rate, Rcpp::Nullable<double> max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose);
RcppExport SEXP _glmbayesCore_rNormalGammaReg_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGammaReg_cpp_export(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rGammaGaussian_cpp_export
Rcpp::List rGammaGaussian_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& alpha, double shape, double rate, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose);
RcppExport SEXP _glmbayesCore_rGammaGaussian_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP wtSEXP, SEXP alphaSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rGammaGaussian_cpp_export(n, y, x, beta, wt, alpha, shape, rate, disp_lower, disp_upper, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rGammaGamma_cpp_export
Rcpp::List rGammaGamma_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& wt, const Rcpp::NumericVector& alpha, double shape, double rate, double max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose);
RcppExport SEXP _glmbayesCore_rGammaGamma_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP betaSEXP, SEXP wtSEXP, SEXP alphaSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rGammaGamma_cpp_export(n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rNormalGLM_std_cpp_export
Rcpp::List rNormalGLM_std_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::List& Envelope, const Rcpp::CharacterVector& family, const Rcpp::CharacterVector& link, int progbar, bool verbose);
RcppExport SEXP _glmbayesCore_rNormalGLM_std_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP EnvelopeSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP progbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Envelope(EnvelopeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rNormalGLM_std_cpp_export(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeSize_cpp_export
Rcpp::List EnvelopeSize_cpp_export(const arma::vec& a, const Rcpp::NumericMatrix& G1, int Gridtype, int n, int n_envopt, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_EnvelopeSize_cpp_export(SEXP aSEXP, SEXP G1SEXP, SEXP GridtypeSEXP, SEXP nSEXP, SEXP n_envoptSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type G1(G1SEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeSize_cpp_export(a, G1, Gridtype, n, n_envopt, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeBuild_cpp_export
Rcpp::List EnvelopeBuild_cpp_export(Rcpp::NumericVector bStar, Rcpp::NumericMatrix A, Rcpp::NumericVector y, Rcpp::NumericMatrix x, Rcpp::NumericMatrix mu, Rcpp::NumericMatrix P, Rcpp::NumericVector alpha, Rcpp::NumericVector wt, std::string family, std::string link, int Gridtype, int n, int n_envopt, bool sortgrid, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_EnvelopeBuild_cpp_export(SEXP bStarSEXP, SEXP ASEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP nSEXP, SEXP n_envoptSEXP, SEXP sortgridSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bStar(bStarSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< std::string >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type sortgrid(sortgridSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeBuild_cpp_export(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeBuild_Ind_Normal_Gamma_cpp_export
Rcpp::List EnvelopeBuild_Ind_Normal_Gamma_cpp_export(const Rcpp::NumericVector& bStar, const Rcpp::NumericMatrix& A, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const std::string& family, const std::string& link, int Gridtype, int n, int n_envopt, bool sortgrid, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_EnvelopeBuild_Ind_Normal_Gamma_cpp_export(SEXP bStarSEXP, SEXP ASEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP GridtypeSEXP, SEXP nSEXP, SEXP n_envoptSEXP, SEXP sortgridSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bStar(bStarSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< bool >::type sortgrid(sortgridSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeBuild_Ind_Normal_Gamma_cpp_export(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeEval_cpp_export
Rcpp::List EnvelopeEval_cpp_export(const Rcpp::NumericMatrix& G4, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const std::string& family, const std::string& link, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_EnvelopeEval_cpp_export(SEXP G4SEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type G4(G4SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeEval_cpp_export(G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeDispersionBuild_cpp_export
Rcpp::List EnvelopeDispersionBuild_cpp_export(const Rcpp::List& Env, double Shape, double Rate, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& alpha, int n_obs, double RSS_post, double RSS_ML, const Rcpp::NumericMatrix& mu, const Rcpp::NumericVector& wt, double max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool verbose, bool use_parallel);
RcppExport SEXP _glmbayesCore_EnvelopeDispersionBuild_cpp_export(SEXP EnvSEXP, SEXP ShapeSEXP, SEXP RateSEXP, SEXP PSEXP, SEXP ySEXP, SEXP xSEXP, SEXP alphaSEXP, SEXP n_obsSEXP, SEXP RSS_postSEXP, SEXP RSS_MLSEXP, SEXP muSEXP, SEXP wtSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP verboseSEXP, SEXP use_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Env(EnvSEXP);
    Rcpp::traits::input_parameter< double >::type Shape(ShapeSEXP);
    Rcpp::traits::input_parameter< double >::type Rate(RateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< double >::type RSS_post(RSS_postSEXP);
    Rcpp::traits::input_parameter< double >::type RSS_ML(RSS_MLSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeDispersionBuild_cpp_export(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeOrchestrator_cpp_export
Rcpp::List EnvelopeOrchestrator_cpp_export(const Rcpp::NumericVector& bstar2, const Rcpp::NumericMatrix& A, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x2, const Rcpp::NumericMatrix& mu2, const Rcpp::NumericMatrix& P2, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, int n, int Gridtype, Rcpp::Nullable<int> n_envopt, double shape, double rate, double RSS_Post2, double RSS_ML, double max_disp_perc, Rcpp::Nullable<double> disp_lower, Rcpp::Nullable<double> disp_upper, bool use_parallel, bool use_opencl, bool verbose);
RcppExport SEXP _glmbayesCore_EnvelopeOrchestrator_cpp_export(SEXP bstar2SEXP, SEXP ASEXP, SEXP ySEXP, SEXP x2SEXP, SEXP mu2SEXP, SEXP P2SEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP nSEXP, SEXP GridtypeSEXP, SEXP n_envoptSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP RSS_Post2SEXP, SEXP RSS_MLSEXP, SEXP max_disp_percSEXP, SEXP disp_lowerSEXP, SEXP disp_upperSEXP, SEXP use_parallelSEXP, SEXP use_openclSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bstar2(bstar2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P2(P2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type n_envopt(n_envoptSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< double >::type RSS_Post2(RSS_Post2SEXP);
    Rcpp::traits::input_parameter< double >::type RSS_ML(RSS_MLSEXP);
    Rcpp::traits::input_parameter< double >::type max_disp_perc(max_disp_percSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_lower(disp_lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type disp_upper(disp_upperSEXP);
    Rcpp::traits::input_parameter< bool >::type use_parallel(use_parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_opencl(use_openclSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeOrchestrator_cpp_export(bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeCentering_cpp_export
Rcpp::List EnvelopeCentering_cpp_export(const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericVector& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& wt, double shape, double rate, int Gridtype, bool verbose);
RcppExport SEXP _glmbayesCore_EnvelopeCentering_cpp_export(SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP offsetSEXP, SEXP wtSEXP, SEXP shapeSEXP, SEXP rateSEXP, SEXP GridtypeSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type Gridtype(GridtypeSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeCentering_cpp_export(y, x, mu, P, offset, wt, shape, rate, Gridtype, verbose));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeSet_Grid_cpp_export
Rcpp::List EnvelopeSet_Grid_cpp_export(const Rcpp::NumericMatrix& GIndex, const Rcpp::NumericMatrix& cbars, const Rcpp::NumericMatrix& Lint);
RcppExport SEXP _glmbayesCore_EnvelopeSet_Grid_cpp_export(SEXP GIndexSEXP, SEXP cbarsSEXP, SEXP LintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type GIndex(GIndexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type cbars(cbarsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Lint(LintSEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeSet_Grid_cpp_export(GIndex, cbars, Lint));
    return rcpp_result_gen;
END_RCPP
}
// EnvelopeSet_LogP_cpp_export
Rcpp::List EnvelopeSet_LogP_cpp_export(const Rcpp::NumericMatrix& logP, const Rcpp::NumericVector& NegLL, const Rcpp::NumericMatrix& cbars, const Rcpp::NumericMatrix& G3);
RcppExport SEXP _glmbayesCore_EnvelopeSet_LogP_cpp_export(SEXP logPSEXP, SEXP NegLLSEXP, SEXP cbarsSEXP, SEXP G3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type logP(logPSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type NegLL(NegLLSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type cbars(cbarsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type G3(G3SEXP);
    rcpp_result_gen = Rcpp::wrap(EnvelopeSet_LogP_cpp_export(logP, NegLL, cbars, G3));
    return rcpp_result_gen;
END_RCPP
}
// rIndepNormalGammaReg_std_cpp_export
Rcpp::List rIndepNormalGammaReg_std_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::List& Envelope, const Rcpp::List& gamma_list, const Rcpp::List& UB_list, const Rcpp::CharacterVector& family, const Rcpp::CharacterVector& link, bool progbar, bool verbose);
RcppExport SEXP _glmbayesCore_rIndepNormalGammaReg_std_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP EnvelopeSEXP, SEXP gamma_listSEXP, SEXP UB_listSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP progbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Envelope(EnvelopeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type UB_list(UB_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rIndepNormalGammaReg_std_cpp_export(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rIndepNormalGammaReg_std_parallel_cpp_export
Rcpp::List rIndepNormalGammaReg_std_parallel_cpp_export(int n, const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& mu, const Rcpp::NumericMatrix& P, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& wt, const Rcpp::Function& f2, const Rcpp::List& Envelope, const Rcpp::List& gamma_list, const Rcpp::List& UB_list, const Rcpp::CharacterVector& family, const Rcpp::CharacterVector& link, bool progbar, bool verbose);
RcppExport SEXP _glmbayesCore_rIndepNormalGammaReg_std_parallel_cpp_export(SEXP nSEXP, SEXP ySEXP, SEXP xSEXP, SEXP muSEXP, SEXP PSEXP, SEXP alphaSEXP, SEXP wtSEXP, SEXP f2SEXP, SEXP EnvelopeSEXP, SEXP gamma_listSEXP, SEXP UB_listSEXP, SEXP familySEXP, SEXP linkSEXP, SEXP progbarSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type f2(f2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Envelope(EnvelopeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gamma_list(gamma_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type UB_list(UB_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rIndepNormalGammaReg_std_parallel_cpp_export(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose));
    return rcpp_result_gen;
END_RCPP
}
// glmb_Standardize_Model_cpp_export
Rcpp::List glmb_Standardize_Model_cpp_export(const Rcpp::NumericVector& y, const Rcpp::NumericMatrix& x, const Rcpp::NumericMatrix& P, const Rcpp::NumericMatrix& bstar, const Rcpp::NumericMatrix& A1);
RcppExport SEXP _glmbayesCore_glmb_Standardize_Model_cpp_export(SEXP ySEXP, SEXP xSEXP, SEXP PSEXP, SEXP bstarSEXP, SEXP A1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type P(PSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type bstar(bstarSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type A1(A1SEXP);
    rcpp_result_gen = Rcpp::wrap(glmb_Standardize_Model_cpp_export(y, x, P, bstar, A1));
    return rcpp_result_gen;
END_RCPP
}
// glmbayesCore_has_opencl_cpp_export
bool glmbayesCore_has_opencl_cpp_export();
RcppExport SEXP _glmbayesCore_glmbayesCore_has_opencl_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(glmbayesCore_has_opencl_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// gpu_names_cpp_export
Rcpp::CharacterVector gpu_names_cpp_export();
RcppExport SEXP _glmbayesCore_gpu_names_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_names_cpp_export());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glmbayesCore_rNormalGLM_cpp_export", (DL_FUNC) &_glmbayesCore_rNormalGLM_cpp_export, 18},
    {"_glmbayesCore_rNormalGLMBlocks_cpp_export", (DL_FUNC) &_glmbayesCore_rNormalGLMBlocks_cpp_export, 19},
    {"_glmbayesCore_rNormalRegBlocks_cpp_export", (DL_FUNC) &_glmbayesCore_rNormalRegBlocks_cpp_export, 13},
    {"_glmbayesCore_block_rNormalReg_cpp_export", (DL_FUNC) &_glmbayesCore_block_rNormalReg_cpp_export, 11},
    {"_glmbayesCore_block_rNormalGLM_cpp_export", (DL_FUNC) &_glmbayesCore_block_rNormalGLM_cpp_export, 17},
    {"_glmbayesCore_two_block_rNormal_reg_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_rNormal_reg_cpp_export, 26},
    {"_glmbayesCore_two_block_rNormal_reg_v2_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_rNormal_reg_v2_cpp_export, 26},
    {"_glmbayesCore_two_block_rNormal_reg_v5_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_rNormal_reg_v5_cpp_export, 32},
    {"_glmbayesCore_two_block_rNormal_reg_staged_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_rNormal_reg_staged_cpp_export, 29},
    {"_glmbayesCore_two_block_build_mu_all_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_build_mu_all_cpp_export, 4},
    {"_glmbayesCore_two_block_block1_prior_with_tau2_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block1_prior_with_tau2_cpp_export, 5},
    {"_glmbayesCore_two_block_block1_iters_mean_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block1_iters_mean_cpp_export, 1},
    {"_glmbayesCore_two_block_batch_tau2_chain_row_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_batch_tau2_chain_row_cpp_export, 2},
    {"_glmbayesCore_two_block_batch_b_assign_slice_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_batch_b_assign_slice_cpp_export, 3},
    {"_glmbayesCore_two_block_batch_iters_ranef_add_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_batch_iters_ranef_add_cpp_export, 3},
    {"_glmbayesCore_two_block_block1_one_chain_draw_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block1_one_chain_draw_cpp_export, 22},
    {"_glmbayesCore_two_block_block1_one_chain_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block1_one_chain_cpp_export, 18},
    {"_glmbayesCore_two_block_block1_one_chain_v2_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block1_one_chain_v2_cpp_export, 12},
    {"_glmbayesCore_two_block_block1_all_chains_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block1_all_chains_cpp_export, 17},
    {"_glmbayesCore_two_block_reorder_b_to_group_levels_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_reorder_b_to_group_levels_cpp_export, 3},
    {"_glmbayesCore_two_block_align_b_to_xhyper_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_align_b_to_xhyper_cpp_export, 3},
    {"_glmbayesCore_two_block_block2_one_chain_cpp_export", (DL_FUNC) &_glmbayesCore_two_block_block2_one_chain_cpp_export, 9},
    {"_glmbayesCore_rNormalReg_cpp_export", (DL_FUNC) &_glmbayesCore_rNormalReg_cpp_export, 14},
    {"_glmbayesCore_rIndepNormalGammaReg_cpp_export", (DL_FUNC) &_glmbayesCore_rIndepNormalGammaReg_cpp_export, 18},
    {"_glmbayesCore_rNormalGammaReg_cpp_export", (DL_FUNC) &_glmbayesCore_rNormalGammaReg_cpp_export, 13},
    {"_glmbayesCore_rGammaGaussian_cpp_export", (DL_FUNC) &_glmbayesCore_rGammaGaussian_cpp_export, 11},
    {"_glmbayesCore_rGammaGamma_cpp_export", (DL_FUNC) &_glmbayesCore_rGammaGamma_cpp_export, 12},
    {"_glmbayesCore_rNormalGLM_std_cpp_export", (DL_FUNC) &_glmbayesCore_rNormalGLM_std_cpp_export, 13},
    {"_glmbayesCore_EnvelopeSize_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeSize_cpp_export, 7},
    {"_glmbayesCore_EnvelopeBuild_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeBuild_cpp_export, 16},
    {"_glmbayesCore_EnvelopeBuild_Ind_Normal_Gamma_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeBuild_Ind_Normal_Gamma_cpp_export, 16},
    {"_glmbayesCore_EnvelopeEval_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeEval_cpp_export, 11},
    {"_glmbayesCore_EnvelopeDispersionBuild_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeDispersionBuild_cpp_export, 17},
    {"_glmbayesCore_EnvelopeOrchestrator_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeOrchestrator_cpp_export, 21},
    {"_glmbayesCore_EnvelopeCentering_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeCentering_cpp_export, 10},
    {"_glmbayesCore_EnvelopeSet_Grid_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeSet_Grid_cpp_export, 3},
    {"_glmbayesCore_EnvelopeSet_LogP_cpp_export", (DL_FUNC) &_glmbayesCore_EnvelopeSet_LogP_cpp_export, 4},
    {"_glmbayesCore_rIndepNormalGammaReg_std_cpp_export", (DL_FUNC) &_glmbayesCore_rIndepNormalGammaReg_std_cpp_export, 15},
    {"_glmbayesCore_rIndepNormalGammaReg_std_parallel_cpp_export", (DL_FUNC) &_glmbayesCore_rIndepNormalGammaReg_std_parallel_cpp_export, 15},
    {"_glmbayesCore_glmb_Standardize_Model_cpp_export", (DL_FUNC) &_glmbayesCore_glmb_Standardize_Model_cpp_export, 5},
    {"_glmbayesCore_glmbayesCore_has_opencl_cpp_export", (DL_FUNC) &_glmbayesCore_glmbayesCore_has_opencl_cpp_export, 0},
    {"_glmbayesCore_gpu_names_cpp_export", (DL_FUNC) &_glmbayesCore_gpu_names_cpp_export, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmbayesCore(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
