# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rNormalGLM_cpp_export <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayesCore_rNormalGLM_cpp_export`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

rNormalGLMBlocks_cpp_export <- function(n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayesCore_rNormalGLMBlocks_cpp_export`, n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

rNormalRegBlocks_cpp_export <- function(n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, Gridtype = 2L) {
    .Call(`_glmbayesCore_rNormalRegBlocks_cpp_export`, n, y, x, offset, wt, dispersion, mu, P_blocks, prior_by_block, row_blocks, f2, f3, Gridtype)
}

block_rNormalReg_cpp_export <- function(n, y, x, block, prior_list, prior_lists, offset, wt, f2, f3, Gridtype = 2L) {
    .Call(`_glmbayesCore_block_rNormalReg_cpp_export`, n, y, x, block, prior_list, prior_lists, offset, wt, f2, f3, Gridtype)
}

block_rNormalGLM_cpp_export <- function(n, y, x, block, prior_list, prior_lists, offset, wt, f2, f3, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayesCore_block_rNormalGLM_cpp_export`, n, y, x, block, prior_list, prior_lists, offset, wt, f2, f3, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

two_block_rNormal_reg_cpp_export <- function(n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, prior_list_block2, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype = 2L, n_envopt = 1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE, progbar = TRUE) {
    .Call(`_glmbayesCore_two_block_rNormal_reg_cpp_export`, n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, prior_list_block2, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar)
}

two_block_rNormal_reg_v2_cpp_export <- function(n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype = 2L, n_envopt = 1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE, progbar = TRUE) {
    .Call(`_glmbayesCore_two_block_rNormal_reg_v2_cpp_export`, n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar)
}

two_block_rNormal_reg_v5_cpp_export <- function(n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype = 2L, n_envopt = 1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE, seed = NULL, seed_offset = 0L, progbar = TRUE, stage_label = "", diag_sweeps = FALSE, fixef_mode = NULL, b_mode = NULL) {
    .Call(`_glmbayesCore_two_block_rNormal_reg_v5_cpp_export`, n, m_convergence, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, seed, seed_offset, progbar, stage_label, diag_sweeps, fixef_mode, b_mode)
}

two_block_rNormal_reg_staged_cpp_export <- function(n_main, m_convergence_main, n_pilot, m_convergence_pilot, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype = 2L, n_envopt = 1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE, progbar_main = TRUE, progbar_pilot = FALSE) {
    .Call(`_glmbayesCore_two_block_rNormal_reg_staged_cpp_export`, n_main, m_convergence_main, n_pilot, m_convergence_pilot, y, x, block, x_hyper, prior_list_block1, dispersion_block1, ddef_block1, pfamily_list, fixef_start, group_levels, family, link, f2, f3, f2_gauss, f3_gauss, offset, wt, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar_main, progbar_pilot)
}

two_block_build_mu_all_cpp_export <- function(x_hyper, fixef, re_names, group_levels) {
    .Call(`_glmbayesCore_two_block_build_mu_all_cpp_export`, x_hyper, fixef, re_names, group_levels)
}

two_block_block1_prior_with_tau2_cpp_export <- function(base_prior, tau2_vec, ptypes, re_names, mu_all) {
    .Call(`_glmbayesCore_two_block_block1_prior_with_tau2_cpp_export`, base_prior, tau2_vec, ptypes, re_names, mu_all)
}

two_block_block1_iters_mean_cpp_export <- function(block_out) {
    .Call(`_glmbayesCore_two_block_block1_iters_mean_cpp_export`, block_out)
}

two_block_batch_fixef_chain_cpp_export <- function(batch_fixef, chain_i, re_names) {
    .Call(`_glmbayesCore_two_block_batch_fixef_chain_cpp_export`, batch_fixef, chain_i, re_names)
}

two_block_batch_tau2_chain_row_cpp_export <- function(batch_tau2, chain_i) {
    .Call(`_glmbayesCore_two_block_batch_tau2_chain_row_cpp_export`, batch_tau2, chain_i)
}

two_block_batch_b_assign_slice_cpp_export <- function(b_store, chain_i, b_draw) {
    .Call(`_glmbayesCore_two_block_batch_b_assign_slice_cpp_export`, b_store, chain_i, b_draw)
}

two_block_batch_iters_ranef_add_cpp_export <- function(iters_ranef, chain_i, iters_mean) {
    .Call(`_glmbayesCore_two_block_batch_iters_ranef_add_cpp_export`, iters_ranef, chain_i, iters_mean)
}

two_block_block1_one_chain_draw_cpp_export <- function(chain_i, batch_fixef, tau2_i, y, Z, groups, offset, wt, x_hyper, re_names, group_levels, ptypes, block1_prior, is_gaussian, f2, f3, f2_gauss, f3_gauss, family, link, Gridtype, n_envopt) {
    .Call(`_glmbayesCore_two_block_block1_one_chain_draw_cpp_export`, chain_i, batch_fixef, tau2_i, y, Z, groups, offset, wt, x_hyper, re_names, group_levels, ptypes, block1_prior, is_gaussian, f2, f3, f2_gauss, f3_gauss, family, link, Gridtype, n_envopt)
}

two_block_block1_one_chain_cpp_export <- function(chain_i, b_store, iters_ranef, batch_fixef, batch_tau2, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add) {
    .Call(`_glmbayesCore_two_block_block1_one_chain_cpp_export`, chain_i, b_store, iters_ranef, batch_fixef, batch_tau2, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add)
}

two_block_block1_one_chain_from_mu_P_cpp_export <- function(mu_all, P, dispersion, ddef, design, family, re_names, group_levels, f2, f3, f2_gauss, f3_gauss) {
    .Call(`_glmbayesCore_two_block_block1_one_chain_from_mu_P_cpp_export`, mu_all, P, dispersion, ddef, design, family, re_names, group_levels, f2, f3, f2_gauss, f3_gauss)
}

two_block_block1_one_chain_v2_cpp_export <- function(fixef_i, tau2_i, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss) {
    .Call(`_glmbayesCore_two_block_block1_one_chain_v2_cpp_export`, fixef_i, tau2_i, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss)
}

two_block_block1_all_chains_v2_internal_cpp_export <- function(fixef, chain_i, tau2, b_store, iters_ranef, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add) {
    .Call(`_glmbayesCore_two_block_block1_all_chains_v2_internal_cpp_export`, fixef, chain_i, tau2, b_store, iters_ranef, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add)
}

two_block_block1_all_chains_v2_internal_loop_cpp_export <- function(n, fixef, tau2, b_in_master, iters_ranef_in, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add, show_bar, progbar_prefix, progbar_finish_newline) {
    .Call(`_glmbayesCore_two_block_block1_all_chains_v2_internal_loop_cpp_export`, n, fixef, tau2, b_in_master, iters_ranef_in, design, block1_prior, family, ptypes, re_names, group_levels, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add, show_bar, progbar_prefix, progbar_finish_newline)
}

two_block_block1_all_chains_cpp_export <- function(n, fixef, tau2, b, iters_ranef, re_names, group_levels, design, block1_prior, family, ptypes, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add, show_bar, progbar_prefix, progbar_finish_newline) {
    invisible(.Call(`_glmbayesCore_two_block_block1_all_chains_cpp_export`, n, fixef, tau2, b, iters_ranef, re_names, group_levels, design, block1_prior, family, ptypes, f2, f3, f2_gauss, f3_gauss, use_cpp_tau2_row, use_cpp_b_slice, use_cpp_iters_ranef_add, show_bar, progbar_prefix, progbar_finish_newline))
}

two_block_reorder_b_to_group_levels_cpp_export <- function(b_draw, block_ids, group_levels) {
    .Call(`_glmbayesCore_two_block_reorder_b_to_group_levels_cpp_export`, b_draw, block_ids, group_levels)
}

two_block_align_b_to_xhyper_cpp_export <- function(b_vec, X_k, group_levels) {
    .Call(`_glmbayesCore_two_block_align_b_to_xhyper_cpp_export`, b_vec, X_k, group_levels)
}

two_block_block2_one_chain_cpp_export <- function(b_i, fixef_rows, tau2_i, iters_i, x_hyper, group_levels, pfamily_list, ptypes, re_names) {
    .Call(`_glmbayesCore_two_block_block2_one_chain_cpp_export`, b_i, fixef_rows, tau2_i, iters_i, x_hyper, group_levels, pfamily_list, ptypes, re_names)
}

rNormalReg_cpp_export <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call(`_glmbayesCore_rNormalReg_cpp_export`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

rIndepNormalGammaReg_cpp_export <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar) {
    .Call(`_glmbayesCore_rIndepNormalGammaReg_cpp_export`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar)
}

rNormalGammaReg_cpp_export <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose = FALSE) {
    .Call(`_glmbayesCore_rNormalGammaReg_cpp_export`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose)
}

rGammaGaussian_cpp_export <- function(n, y, x, beta, wt, alpha, shape, rate, disp_lower = NULL, disp_upper = NULL, verbose = FALSE) {
    .Call(`_glmbayesCore_rGammaGaussian_cpp_export`, n, y, x, beta, wt, alpha, shape, rate, disp_lower, disp_upper, verbose)
}

rGammaGamma_cpp_export <- function(n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower = NULL, disp_upper = NULL, verbose = FALSE) {
    .Call(`_glmbayesCore_rGammaGamma_cpp_export`, n, y, x, beta, wt, alpha, shape, rate, max_disp_perc, disp_lower, disp_upper, verbose)
}

rNormalGLM_std_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L, verbose = FALSE) {
    .Call(`_glmbayesCore_rNormalGLM_std_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose)
}

EnvelopeSize_cpp_export <- function(a, G1, Gridtype, n, n_envopt, use_opencl, verbose) {
    .Call(`_glmbayesCore_EnvelopeSize_cpp_export`, a, G1, Gridtype, n, n_envopt, use_opencl, verbose)
}

EnvelopeBuild_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose) {
    .Call(`_glmbayesCore_EnvelopeBuild_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeBuild_Ind_Normal_Gamma_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, n_envopt = -1L, sortgrid = FALSE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayesCore_EnvelopeBuild_Ind_Normal_Gamma_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeEval_cpp_export <- function(G4, y, x, mu, P, alpha, wt, family, link, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayesCore_EnvelopeEval_cpp_export`, G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose)
}

EnvelopeDispersionBuild_cpp_export <- function(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc = 0.99, disp_lower = NULL, disp_upper = NULL, verbose = FALSE, use_parallel = TRUE) {
    .Call(`_glmbayesCore_EnvelopeDispersionBuild_cpp_export`, Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel)
}

EnvelopeOrchestrator_cpp_export <- function(bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose) {
    .Call(`_glmbayesCore_EnvelopeOrchestrator_cpp_export`, bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose)
}

EnvelopeCentering_cpp_export <- function(y, x, mu, P, offset, wt, shape, rate, Gridtype = 2L, verbose = FALSE) {
    .Call(`_glmbayesCore_EnvelopeCentering_cpp_export`, y, x, mu, P, offset, wt, shape, rate, Gridtype, verbose)
}

BlockEnvelopeCentering_cpp_export <- function(y, x, block, prior_list, prior_lists, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, p_re = -1L, n_rss_iter = 10L, verbose = FALSE) {
    .Call(`_glmbayesCore_BlockEnvelopeCentering_cpp_export`, y, x, block, prior_list, prior_lists, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, p_re, n_rss_iter, verbose)
}

BlockEnvelopeBuild_cpp_export <- function(centering_out, y, x, block, prior_list, prior_lists, offset, wt, max_disp_perc, disp_lower, disp_upper, n = 1L, Gridtype = 3L, n_envopt = -1L, RSS_ML = NA_real_, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayesCore_BlockEnvelopeBuild_cpp_export`, centering_out, y, x, block, prior_list, prior_lists, offset, wt, max_disp_perc, disp_lower, disp_upper, n, Gridtype, n_envopt, RSS_ML, use_parallel, use_opencl, verbose)
}

EnvelopeSet_Grid_cpp_export <- function(GIndex, cbars, Lint) {
    .Call(`_glmbayesCore_EnvelopeSet_Grid_cpp_export`, GIndex, cbars, Lint)
}

EnvelopeSet_LogP_cpp_export <- function(logP, NegLL, cbars, G3) {
    .Call(`_glmbayesCore_EnvelopeSet_LogP_cpp_export`, logP, NegLL, cbars, G3)
}

rIndepNormalGammaReg_std_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_glmbayesCore_rIndepNormalGammaReg_std_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

rIndepNormalGammaReg_std_parallel_cpp_export <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar = TRUE, verbose = FALSE) {
    .Call(`_glmbayesCore_rIndepNormalGammaReg_std_parallel_cpp_export`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

glmb_Standardize_Model_cpp_export <- function(y, x, P, bstar, A1) {
    .Call(`_glmbayesCore_glmb_Standardize_Model_cpp_export`, y, x, P, bstar, A1)
}

glmbayesCore_has_opencl_cpp_export <- function() {
    .Call(`_glmbayesCore_glmbayesCore_has_opencl_cpp_export`)
}

gpu_names_cpp_export <- function() {
    .Call(`_glmbayesCore_gpu_names_cpp_export`)
}

