# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EnvelopeSize_export <- function(a, G1, Gridtype, n, n_envopt, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeSize_export`, a, G1, Gridtype, n, n_envopt, use_opencl, verbose)
}

EnvelopeBuild_cpp_export <- function(bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeBuild_cpp_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeEval_export <- function(G4, y, x, mu, P, alpha, wt, family, link, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeEval_export`, G4, y, x, mu, P, alpha, wt, family, link, use_opencl, verbose)
}

EnvelopeBuild_Ind_Normal_Gamma_export <- function(bStar, A, y, x, mu, P, alpha, wt, family = "binomial", link = "logit", Gridtype = 2L, n = 1L, n_envopt = -1L, sortgrid = FALSE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_EnvelopeBuild_Ind_Normal_Gamma_export`, bStar, A, y, x, mu, P, alpha, wt, family, link, Gridtype, n, n_envopt, sortgrid, use_opencl, verbose)
}

EnvelopeDispersionBuild_cpp_export <- function(Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc = 0.99, disp_lower = NULL, disp_upper = NULL, verbose = FALSE, use_parallel = TRUE) {
    .Call(`_glmbayes_EnvelopeDispersionBuild_cpp_export`, Env, Shape, Rate, P, y, x, alpha, n_obs, RSS_post, RSS_ML, mu, wt, max_disp_perc, disp_lower, disp_upper, verbose, use_parallel)
}

EnvelopeOrchestrator_cpp_export <- function(bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose) {
    .Call(`_glmbayes_EnvelopeOrchestrator_cpp_export`, bstar2, A, y, x2, mu2, P2, alpha, wt, n, Gridtype, n_envopt, shape, rate, RSS_Post2, RSS_ML, max_disp_perc, disp_lower, disp_upper, use_parallel, use_opencl, verbose)
}

setlogP_export <- function(logP, NegLL, cbars, G3) {
    .Call(`_glmbayes_setlogP_export`, logP, NegLL, cbars, G3)
}

Set_Grid_export <- function(GIndex, cbars, Lint) {
    .Call(`_glmbayes_Set_Grid_export`, GIndex, cbars, Lint)
}

rss_face_at_disp_export <- function(dispersion, cache, cbars_j, y, x, alpha, wt) {
    .Call(`_glmbayes_rss_face_at_disp_export`, dispersion, cache, cbars_j, y, x, alpha, wt)
}

UB2_export <- function(dispersion, cache, cbars_j, y, x, alpha, wt, rss_min_global) {
    .Call(`_glmbayes_UB2_export`, dispersion, cache, cbars_j, y, x, alpha, wt, rss_min_global)
}

load_kernel_source_wrapper_export <- function(relative_path, package = "glmbayes") {
    .Call(`_glmbayes_load_kernel_source_wrapper_export`, relative_path, package)
}

load_kernel_library_wrapper_export <- function(subdir, package = "glmbayes", verbose = FALSE) {
    .Call(`_glmbayes_load_kernel_library_wrapper_export`, subdir, package, verbose)
}

has_opencl_export <- function() {
    .Call(`_glmbayes_has_opencl_export`)
}

get_opencl_core_count_export <- function() {
    .Call(`_glmbayes_get_opencl_core_count_export`)
}

gpu_names_export <- function() {
    .Call(`_glmbayes_gpu_names_export`)
}

.rindep_norm_gamma_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

.rindep_norm_gamma_reg_std_parallel_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_std_parallel_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, gamma_list, UB_list, family, link, progbar, verbose)
}

rindep_norm_gamma_reg_cpp <- function(n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar) {
    .Call(`_glmbayes_rindep_norm_gamma_reg_cpp`, n, y, x, mu, P, offset, wt, shape, rate, max_disp_perc, disp_lower, disp_upper, Gridtype, n_envopt, use_parallel, use_opencl, verbose, progbar)
}

.glmb_Standardize_Model_cpp <- function(y, x, P, bstar, A1) {
    .Call(`_glmbayes_glmb_Standardize_Model`, y, x, P, bstar, A1)
}

.rnnorm_reg_std_cpp <- function(n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar = 1L, verbose = FALSE) {
    .Call(`_glmbayes_rnnorm_reg_std_cpp`, n, y, x, mu, P, alpha, wt, f2, Envelope, family, link, progbar, verbose)
}

.rnnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "binomial", link = "logit", Gridtype = 2L, n_envopt = -1L, use_parallel = TRUE, use_opencl = FALSE, verbose = FALSE) {
    .Call(`_glmbayes_rnnorm_reg_cpp`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype, n_envopt, use_parallel, use_opencl, verbose)
}

.rnorm_reg_cpp <- function(n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family = "gaussian", link = "identity", Gridtype = 2L) {
    .Call(`_glmbayes_rnorm_reg_cpp`, n, y, x, mu, P, offset, wt, dispersion, f2, f3, start, family, link, Gridtype)
}

